// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdX6M-CGjJFTjhKrRC92FP5qkXxPyY8mg',
    appId: '1:919457662974:web:747d1a28fa995733b662af',
    messagingSenderId: '919457662974',
    projectId: 'plates-it-forward',
    authDomain: 'plates-it-forward.firebaseapp.com',
    databaseURL:
        'https://plates-it-forward-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plates-it-forward.appspot.com',
    measurementId: 'G-CG6FLK0X4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOOwTM70bqCT7kyjo-I81EBKApYgkkidI',
    appId: '1:919457662974:android:4b407805abf6aeabb662af',
    messagingSenderId: '919457662974',
    projectId: 'plates-it-forward',
    databaseURL:
        'https://plates-it-forward-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plates-it-forward.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqbc1APNcVe8gZ8kdXx35q7no69qaFvc0',
    appId: '1:919457662974:ios:a65d7b89f4ac6fbab662af',
    messagingSenderId: '919457662974',
    projectId: 'plates-it-forward',
    databaseURL:
        'https://plates-it-forward-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plates-it-forward.appspot.com',
    iosClientId:
        '919457662974-4ajrc00sirljlmlj3tlga6esh0s66ru3.apps.googleusercontent.com',
    iosBundleId: 'com.plateItForward.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqbc1APNcVe8gZ8kdXx35q7no69qaFvc0',
    appId: '1:919457662974:ios:a65d7b89f4ac6fbab662af',
    messagingSenderId: '919457662974',
    projectId: 'plates-it-forward',
    databaseURL:
        'https://plates-it-forward-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plates-it-forward.appspot.com',
    iosClientId:
        '919457662974-4ajrc00sirljlmlj3tlga6esh0s66ru3.apps.googleusercontent.com',
    iosBundleId: 'com.plateItForward.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdX6M-CGjJFTjhKrRC92FP5qkXxPyY8mg',
    appId: '1:919457662974:web:7aad3d89f2a97c50b662af',
    messagingSenderId: '919457662974',
    projectId: 'plates-it-forward',
    authDomain: 'plates-it-forward.firebaseapp.com',
    databaseURL:
        'https://plates-it-forward-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plates-it-forward.appspot.com',
    measurementId: 'G-G3WDB3XSEF',
  );
}
