// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdX6M-CGjJFTjhKrRC92FP5qkXxPyY8mg',
    appId: '1:919457662974:web:f45f22e05aa66d2bb662af',
    messagingSenderId: '919457662974',
    projectId: 'plates-it-forward',
    authDomain: 'plates-it-forward.firebaseapp.com',
    storageBucket: 'plates-it-forward.appspot.com',
    measurementId: 'G-TFS8W2MZFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOOwTM70bqCT7kyjo-I81EBKApYgkkidI',
    appId: '1:919457662974:android:7ce8c98325bc5645b662af',
    messagingSenderId: '919457662974',
    projectId: 'plates-it-forward',
    storageBucket: 'plates-it-forward.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqbc1APNcVe8gZ8kdXx35q7no69qaFvc0',
    appId: '1:919457662974:ios:211f7d44e7740065b662af',
    messagingSenderId: '919457662974',
    projectId: 'plates-it-forward',
    storageBucket: 'plates-it-forward.appspot.com',
    iosBundleId: 'com.example.platesForward',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqbc1APNcVe8gZ8kdXx35q7no69qaFvc0',
    appId: '1:919457662974:ios:689adca3ade8bab0b662af',
    messagingSenderId: '919457662974',
    projectId: 'plates-it-forward',
    storageBucket: 'plates-it-forward.appspot.com',
    iosBundleId: 'com.example.platesForward.RunnerTests',
  );
}
